modified_genome: "neurog2.fa"
modified_gtf: "neurog2.gtf"
modified_tss_bed: "neurog2_tss.bed" 
# Input files
ctrl_fragments: "TH1_atac_fragments.tsv.gz"
trt_fragments: "TH2_atac_fragments.tsv.gz"
chrom_sizes: "neurog2.chrom.sizes"
samples:
  - TH1
  - TH2
samples_file: "samples.tsv" 
# Labels
ctrl_name: "Control"
trt_name: "OE"
PROJ_NAME: "Neurog2"
RNA_Barcodes: "scRNA_barcodes.csv"
annotations_file: "annotations.txt"
#params 
qc_cmd: "pycistopic_qc_commands.sh"

MALLET_PATH: "/nfs/turbo/umms-thahoang/sherine/tools/Mallet-202108/bin/mallet"
#Thresholds

uniqFrag: 200
minTSS: 0.1
minFrip: 0.0
blacklist: "mm10-blacklist.v2.bed"

adjpval_thr: 0.05
log2fc_thr: 0.5
# Output
out_dir: "scenicOuts"

# Resources
n_cpu: 8



#size of the modified genome
g: 2730873821

#Marker Genes
markers: "mouse_markers.txt"


CELL_TYPES: 
  - MG
  - MGPC
  - Rod
  - Microglia
  - BC
  - Cones
  - AC

#consensus 
combined_bed: "all_combined.bed"
consensus_bed: "final_consensus.bed" 

