modified_genome: "neurog2.fa"
modified_gtf: "neurog2.gtf"
modified_tss_bed: "neurog2_tss.bed" 
# Input files
ctrl_fragments: "TH1_atac_fragments.tsv.gz"
trt_fragments: "TH2_atac_fragments.tsv.gz"
chrom_sizes: "neurog2.chrom.sizes"

# Labels
ctrl_name: "Control"
trt_name: "OE"


#params 
qc_cmd: "pycistopic_qc_commands.sh"

#Thresholds

minTSS: 0.1
minFrag: 200
minFrip: 0.0


# Output
out_dir: "scenicOuts"

# Resources
n_cpu: 4

#size of the modified genome
g: 2730873821


#consensus 
combined_bed: "all_combined.bed"
consensus_bed: "final_consensus.bed" 


